<a href="https://colab.research.google.com/github/hemangikariya/ML-Lab-Assignments/blob/main/Assignment-3/25MCA30048_Hemangi_PythonAssignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. E-Commerce Customer Purchase Analysis with pandas**

**Part A: Data Exploration**

1. Load the dataset into a DataFrame.

In [2]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Ecommerce_Purchases - Ecommerce_Purchases.csv")

2. Display the first and last five records.

In [3]:
df.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6.011929e+15,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3.337758e+15,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",6.759577e+11,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6.011580e+15,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6.011457e+15,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [5]:
df.tail()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9995,"966 Castaneda Locks\nWest Juliafurt, CO 96415",92 XI,PM,Mozilla/5.0 (Windows NT 5.1) AppleWebKit/5352 ...,Randall-Sloan,3.429450e+14,03/22,838,JCB 15 digit,iscott@wade-garner.com,Printmaker,29.73.197.114,it,82.21
9996,"832 Curtis Dam Suite 785\nNorth Edwardburgh, T...",41 JY,AM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Hale, Collins and Wilson",2.100332e+14,07/25,207,JCB 16 digit,mary85@hotmail.com,Energy engineer,121.133.168.51,pt,25.63
9997,Unit 4434 Box 6343\nDPO AE 28026-0283,74 Zh,AM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Anderson Ltd,6.011540e+15,05/21,1,VISA 16 digit,tyler16@gmail.com,Veterinary surgeon,156.210.0.254,el,83.98
9998,"0096 English Rest\nRoystad, IA 12457",74 cL,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_8;...,Cook Inc,1.800033e+14,11/17,987,American Express,elizabethmoore@reid.net,Local government officer,55.78.26.143,es,38.84
9999,"40674 Barrett Stravenue\nGrimesville, WI 79682",64 Hr,AM,Mozilla/5.0 (X11; Linux i686; rv:1.9.5.20) Gec...,Greene Inc,4.139973e+15,02/19,302,JCB 15 digit,rachelford@vaughn.com,"Embryologist, clinical",176.119.198.199,el,67.59

3. Find:

○ Number of rows and columns

In [7]:
df.shape

(10000, 14)

○ Data types

In [8]:
df.dtypes

Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card         float64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  float64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(2), int64(1), object(11)
memory usage: 1.1+ MB

○ Missing values

In [10]:
df.isnull().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

○ Duplicate records

In [11]:
df.duplicated().sum()

np.int64(0)

# **Part B: Customer Analytics**

**Perform the following analyses:**

1. Find the average, maximum, and minimum purchase price.

In [12]:
# Average Purchase Price
df["Purchase Price"].mean()

np.float64(50.347302)

In [13]:
# Maximum Purchase Price
df["Purchase Price"].max()

99.99

In [14]:
# Minimum Purchase Price
df["Purchase Price"].min()

0.0

2. Identify the top 10 most expensive purchases.

In [15]:
df.sort_values(by="Purchase Price",ascending=False).head(10)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
2092,"63773 Shelton Greens\nAshleyton, MA 00493",56 lu,AM,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,Pitts Group,4.292741e+12,06/18,824,Maestro,heatherwoodard@lloyd.com,"Surveyor, hydrographic",172.197.216.229,el,99.99
7807,"PSC 6177, Box 1004\nAPO AA 57143-1269",64 Nf,AM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_4)...,"Porter, Johnson and Pratt",3.010939e+13,11/25,918,VISA 16 digit,kelli72@gmail.com,"Surveyor, insurance",89.51.92.242,de,99.99
9856,"058 Miranda Locks Suite 792\nPort Davidstad, P...",73 IW,PM,Mozilla/5.0 (Windows NT 5.0) AppleWebKit/5360 ...,Olson-Navarro,6.011037e+15,03/18,757,American Express,brendastewart@dalton.info,Site engineer,96.79.250.154,de,99.97
7604,"672 James Oval\nNew Davidview, KS 91202",07 dT,PM,Mozilla/5.0 (Windows 98; Win 9x 4.90; it-IT; r...,Fitzpatrick Group,5.038704e+11,05/24,312,JCB 15 digit,mjenkins@gmail.com,"Teacher, primary school",192.227.38.104,el,99.95
3844,"27148 Kathy Cliff Apt. 400\nEast Jillton, TX 5...",37 ou,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,King and Sons,3.088953e+15,04/17,493,Mastercard,lpowell@yahoo.com,Television camera operator,110.244.150.130,el,99.93
2316,"408 Russell Club\nSouth Thomas, MT 73554-8846",82 iO,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows 95;...,Bond-Oconnor,2.100656e+14,08/22,628,Voyager,vegaallen@gmail.com,Careers adviser,111.5.222.164,it,99.92
6263,"PSC 1273, Box 3037\nAPO AA 11854-3422",93 HJ,PM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Fisher-Guerrero,4.363719e+12,04/24,592,Mastercard,david10@dodson-warner.com,Tree surgeon,158.196.81.143,fr,99.92
4839,"PSC 2750, Box 0268\nAPO AP 40163-4232",02 be,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_8...,"Powell, Martin and Henry",3.337680e+15,02/19,502,JCB 16 digit,karenrichardson@yahoo.com,"Surveyor, mining",77.88.25.173,de,99.91
4148,"5382 Nicole Via Apt. 447\nMartinshire, AS 9397...",74 OR,PM,Opera/8.39.(X11; Linux i686; en-US) Presto/2.9...,Fisher-Marshall,1.800735e+14,06/18,535,VISA 16 digit,williamthomas@gmail.com,"Nurse, learning disability",146.225.23.148,pt,99.90
3079,"7728 Kirby Flats Suite 330\nTracymouth, OK 06688",52 sy,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4;...,Walker Group,8.699114e+14,06/20,897,JCB 16 digit,zbailey@gmail.com,Environmental manager,161.162.101.178,de,99.90

3. Count customers whose preferred language is:

○ English | French | German

In [16]:
# English
df[df["Language"]=="en"].shape[0]

1098

In [18]:
# French
df[df["Language"]=="fr"].shape[0]

1097

In [19]:
# German
df[df["Language"]=="de"].shape[0]

1155

In [20]:
df["Language"].value_counts()

Language
de    1155
ru    1155
el    1137
pt    1118
en    1098
fr    1097
es    1095
it    1086
zh    1059
Name: count, dtype: int64

4. Find the number of customers using:

○ Visa | MasterCard | American Express

In [21]:
# Visa
df[df["CC Provider"].str.contains("Visa",case=False)].shape[0]

2492

In [22]:
# MasterCard
df[df["CC Provider"].str.contains("Mastercard",case=False)].shape[0]

816

In [23]:
# American Express
df[df["CC Provider"].str.contains("American Express",case=False)].shape[0]

849

5. Determine the five most common job titles.

In [24]:
df["Job"].value_counts().head()

Job
Interior and spatial designer        31
Lawyer                               30
Social researcher                    28
Research officer, political party    27
Designer, jewellery                  27
Name: count, dtype: int64

# **Part C: Business Insights**

1. Which email provider has the highest number of users?

In [27]:
df["Email Provider"]=df["Email"].apply(lambda x:x.split("@")[1])

In [28]:
df["Email Provider"].value_counts().head()

Email Provider
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

**2. Calculate:**

○ Total sales | Average sales | Median purchase price

In [29]:
# Total Sales
df["Purchase Price"].sum()

np.float64(503473.02)

In [30]:
# Average Sales
df["Purchase Price"].mean()

np.float64(50.347302)

In [31]:
# Median
df["Purchase Price"].median()

50.504999999999995

**3. Create a new column:**
Purchase Category based on Purchase Price:
Price   Category
< 30    Low
30–60   Medium
 > 60    High

In [33]:
def category(price):
  if price<30:
    return"Low"
  elif price<=60:
    return"Medium"
  else:
    return "High"

  df["Purchase Category"]=df["Purchase Price"].apply(category)

# Using Lambda
# df["Purchase Category"]=df["Purchase Price"].apply(
# lambda x:"Low" if x<30 else ("Medium" if x<=60 else "High"))

4. Show the percentage of customers in each category.

In [34]:
df["Purchase Category"].value_counts(normalize=True)*100

Purchase Category
High      40.52
Low       29.84
Medium    29.64
Name: proportion, dtype: float64

# **Part D: Advanced Pandas**

**Use:**

● groupby()
● sort_values()
● value_counts()
● apply()
● lambda
● isin()

1. Which company has the highest average purchase price?

In [35]:
df.groupby("Company")["Purchase Price"].mean().sort_values(ascending=False).head(1)

Company
Pitts Group    99.99
Name: Purchase Price, dtype: float64

2. Which credit card provider contributes the highest revenue?

In [36]:
df.groupby("CC Provider")["Purchase Price"].sum().sort_values(ascending=False)

CC Provider
VISA 16 digit                  85528.86
JCB 16 digit                   84597.33
JCB 15 digit                   44376.60
Voyager                        43085.77
American Express               42865.52
Maestro                        42620.78
Discover                       42208.13
Mastercard                     40835.10
VISA 13 digit                  39976.54
Diners Club / Carte Blanche    37378.39
Name: Purchase Price, dtype: float64

3. Which browser users spend the most?

In [41]:
df.groupby("Browser")["Purchase Price"].mean().sort_values(ascending=False)

Browser
Opera      50.930376
Mozilla    50.194543
Name: Purchase Price, dtype: float64

# **2. SF Employee Salary Analysis with pandas**

**Part A: Data Understanding**

1. Import the dataset.

In [42]:
import pandas as pd

salary=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Salaries - Salaries.csv")

**2. Display:**

○ Head
○ Tail
○ Shape
○ Data types
○ Summary statistics

In [43]:
# Head
salary.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [44]:
# Tail
salary.tail()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148649,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [45]:
# Shape
salary.shape

(148654, 13)

In [46]:
# Data Types
salary.dtypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay             float64
OvertimePay         float64
OtherPay            float64
Benefits            float64
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status              float64
dtype: object

In [47]:
# Summary Statistics
salary.describe()

,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Status
count,148654.000000,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000,0.0,0.0
mean,74327.500000,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643,NaN,NaN
std,42912.857795,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538,NaN,NaN
min,1.000000,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000,NaN,NaN
25%,37164.250000,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000,NaN,NaN
50%,74327.500000,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000,NaN,NaN
75%,111490.750000,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000,NaN,NaN
max,148654.000000,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000,NaN,NaN

# **Part B: Salary Analysis**

**Find:**

1. Highest salary
2. Lowest salary
3. Average BasePay
4. Average OvertimePay
5. Average TotalPayBenefits
6. Employee receiving the maximum TotalPayBenefits

In [48]:
# 1. Highest salary
salary["TotalPayBenefits"].max()

567595.43